version: "3.8"
services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: fpv
      POSTGRES_PASSWORD: fpv
      POSTGRES_DB: fpv
      
    ports: ["5432:5432"]
    volumes:
    - db-data:/var/lib/postgresql/data


  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
    - "9000:9000"
    - "9001:9001"
    volumes:
    - minio-data:/data

  app:
    build: .
    env_file: .env
    volumes:
    - ./:/app
    depends_on: [db, minio]
    # command: ["resume"]
    command: CMD ["python3", "-m", "src.cli.main", "crawl"]

volumes:
  db-data:
  minio-data: